package codegen

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . ColumnsRepository

// GENERATED BY CODEGEN. DO NOT EDIT.
/* ColumnsRepository interface definition. */
type ColumnsRepository interface {
	Create(data *Columns) error
	Update(data *Columns) error
	Delete(data *Columns) error

	// ^^ END OF GENERATED BY CODEGEN. DO NOT EDIT. ^^
	QueryBySchemaAndTable(schema, table string) ([]*Columns, error)
}
