package codegen

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . ColumnsRepository

// GENERATED BY CODEGEN.
/* ColumnsRepository interface definition. */
type ColumnsRepository interface {
	Create(data *Columns) error
	Update(data *Columns) error
	UpdatePartial(data *ColumnsPartial) error
	Upsert(data []*Columns) error
	Delete(data *Columns) error

	// ^^ END OF GENERATED BY CODEGEN. ^^
	QueryBySchemaAndTable(schema, table string) ([]*Columns, error)
}
