package codegen

// GENERATED BY CODEGEN.
	
// Constants for table columns. 
const (

			// Columns for table information_schema.COLUMNS
					COLUMNS_TABLECATALOG = iota
					COLUMNS_TABLESCHEMA
					COLUMNS_TABLENAME
					COLUMNS_COLUMNNAME
					COLUMNS_ORDINALPOSITION
					COLUMNS_COLUMNDEFAULT
					COLUMNS_ISNULLABLE
					COLUMNS_DATATYPE
					COLUMNS_CHARACTERMAXIMUMLENGTH
					COLUMNS_CHARACTEROCTETLENGTH
					COLUMNS_NUMERICPRECISION
					COLUMNS_NUMERICSCALE
					COLUMNS_DATETIMEPRECISION
					COLUMNS_CHARACTERSETNAME
					COLUMNS_COLLATIONNAME
					COLUMNS_COLUMNTYPE
					COLUMNS_COLUMNKEY
					COLUMNS_EXTRA
					COLUMNS_PRIVILEGES
					COLUMNS_COLUMNCOMMENT
					COLUMNS_GENERATIONEXPRESSION
		
			// Columns for table information_schema.KEYCOLUMNUSAGE
					KEYCOLUMNUSAGE_CONSTRAINTCATALOG
					KEYCOLUMNUSAGE_CONSTRAINTSCHEMA
					KEYCOLUMNUSAGE_CONSTRAINTNAME
					KEYCOLUMNUSAGE_TABLECATALOG
					KEYCOLUMNUSAGE_TABLESCHEMA
					KEYCOLUMNUSAGE_TABLENAME
					KEYCOLUMNUSAGE_COLUMNNAME
					KEYCOLUMNUSAGE_ORDINALPOSITION
					KEYCOLUMNUSAGE_POSITIONINUNIQUECONSTRAINT
					KEYCOLUMNUSAGE_REFERENCEDTABLESCHEMA
					KEYCOLUMNUSAGE_REFERENCEDTABLENAME
					KEYCOLUMNUSAGE_REFERENCEDCOLUMNNAME
		
			// Columns for table information_schema.STATISTICS
					STATISTICS_TABLECATALOG
					STATISTICS_TABLESCHEMA
					STATISTICS_TABLENAME
					STATISTICS_NONUNIQUE
					STATISTICS_INDEXSCHEMA
					STATISTICS_INDEXNAME
					STATISTICS_SEQININDEX
					STATISTICS_COLUMNNAME
					STATISTICS_COLLATION
					STATISTICS_CARDINALITY
					STATISTICS_SUBPART
					STATISTICS_PACKED
					STATISTICS_NULLABLE
					STATISTICS_INDEXTYPE
					STATISTICS_COMMENT
					STATISTICS_INDEXCOMMENT
					STATISTICS_ISVISIBLE
					STATISTICS_EXPRESSION
		
			// Columns for table information_schema.TABLES
					TABLES_TABLECATALOG
					TABLES_TABLESCHEMA
					TABLES_TABLENAME
					TABLES_TABLETYPE
					TABLES_ENGINE
					TABLES_VERSION
					TABLES_ROWFORMAT
					TABLES_TABLEROWS
					TABLES_AVGROWLENGTH
					TABLES_DATALENGTH
					TABLES_MAXDATALENGTH
					TABLES_INDEXLENGTH
					TABLES_DATAFREE
					TABLES_AUTOINCREMENT
					TABLES_CREATETIME
					TABLES_UPDATETIME
					TABLES_CHECKTIME
					TABLES_TABLECOLLATION
					TABLES_CHECKSUM
					TABLES_CREATEOPTIONS
					TABLES_TABLECOMMENT
		

			// Columns for table fake_benchmark.Person
					Person_ID
					Person_Name
		
			// Columns for table fake_benchmark.Tag
					Tag_ID
					Tag_Name
		
			// Columns for table fake_benchmark.Pet
					Pet_ID
					Pet_PersonID
					Pet_TagID
					Pet_Species
		
			// Columns for table fake_benchmark.Extensive
					Extensive_ID
					Extensive_Tinyint
					Extensive_TinyintUnsigned
					Extensive_TinyintNull
					Extensive_Smallint
					Extensive_SmallintUnsigned
					Extensive_SmallintNull
					Extensive_Int
					Extensive_IntNull
					Extensive_IntUnsigned
					Extensive_Bigint
					Extensive_BigintNull
					Extensive_BigintUnsigned
					Extensive_Varchar
					Extensive_VarcharNull
					Extensive_Float
					Extensive_FloatNull
					Extensive_Double
					Extensive_DoubleNull
					Extensive_Decimal
					Extensive_DecimalNull
					Extensive_Numeric
					Extensive_NumericNull
					Extensive_CreatedAt
					Extensive_UpdatedAt
					Extensive_Tinyint1
					Extensive_Tinyint1Null
					Extensive_Year
					Extensive_YearNull
					Extensive_Date
					Extensive_DateNull
					Extensive_Time
					Extensive_TimeNull
					Extensive_Datetime
					Extensive_DatetimeNull
					Extensive_Timestamp
					Extensive_TimestampNull
					Extensive_Char
					Extensive_CharNull
					Extensive_Tinytext
					Extensive_TinytextNull
					Extensive_Text
					Extensive_TextNull
					Extensive_Mediumtext
					Extensive_MediumtextNull
					Extensive_Longtext
					Extensive_LongtextNull
					Extensive_Binary
					Extensive_BinaryNull
					Extensive_Varbinary
					Extensive_VarbinaryNull
					Extensive_Tinyblob
					Extensive_TinyblobNull
					Extensive_Blob
					Extensive_BlobNull
					Extensive_Mediumblob
					Extensive_MediumblobNull
					Extensive_Longblob
					Extensive_LongblobNull
		

)

 // ^^ END OF GENERATED BY CODEGEN. ^^
