package codegen

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . ExtensiveRepository

// GENERATED BY CODEGEN.
/* ExtensiveRepository interface definition. */
type ExtensiveRepository interface {
	Create(data *Extensive) error
	Update(data *Extensive) error
	UpdatePartial(data *ExtensivePartial) error
	Upsert(data []*Extensive) error
	Delete(data *Extensive) error
	OneByID(id int) (*Extensive, error)

	// ^^ END OF GENERATED BY CODEGEN. ^^
}
