package codegen

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . PetRepository

// GENERATED BY CODEGEN.
/* PetRepository interface definition. */
type PetRepository interface {
	Create(ctx *Context, data *Pet) error
	Update(ctx *Context, data *Pet) error
	UpdatePartial(ctx *Context, data *PetPartial) error
	Delete(ctx *Context, data *Pet) error
	OneByID(ctx *Context, id int) (*Pet, error)

	// ^^ END OF GENERATED BY CODEGEN. ^^
}
