package codegen

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . StatisticsRepository

// GENERATED BY CODEGEN. DO NOT EDIT.
/* StatisticsRepository interface definition. */
type StatisticsRepository interface {
	Create(data *Statistics) error
	Update(data *Statistics) error
	UpdatePartial(data *StatisticsPartial) error
	Delete(data *Statistics) error

	// ^^ END OF GENERATED BY CODEGEN. DO NOT EDIT. ^^
	IndexNameBySchemaAndTable(schema, table string) ([]*Statistics, error)
	QueryBySchemaAndTableAndIndex(schema, table, index string) ([]*Statistics, error)
}
