package codegen

//go:generate go run github.com/maxbrunsfeld/counterfeiter/v6 . TablesRepository

// GENERATED BY CODEGEN.
/* TABLESRepository interface definition. */
type TABLESRepository interface {
		
		
		
		

	// ^^ END OF GENERATED BY CODEGEN. ^^
	QueryBySchema(ctx *Context, schema string) ([]*Tables, error)
}
