package codegen

// TGlobalType template
func TGlobalType(bb *GenBuffer, conf *Config) {

	bb.S("// GENERATED BY CODEGEN. DO NOT EDIT.")
	bb.NewLine()
	bb.NewLine()
	bb.Line("// Constants for table columns.")
	bb.Line("const (")
	for i, s := range conf.Schemas {
		for j, t := range s.Tables {
			bb.Line(`// Columns for table `, s.Name, ".", t.Title)
			for k, f := range t.Fields {
				if i == 0 && j == 0 && k == 0 {
					bb.Line(t.Title + f.Title + " = iota")
				} else {
					bb.Line(t.Title + f.Title)
				}
			}
		}
	}
	bb.Line(")")
	bb.NewLine()

	bb.NewLine()
	bb.S("// ^^ END OF GENERATED BY CODEGEN. DO NOT EDIT. ^^")
	bb.NewLine()
}
