package mysql

import (
	"database/sql"
	"errors"
	"io"
	"math/big"

	codegen "bitbucket.org/codegen"

	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/seambiz/seambiz/sdb"
)

// GENERATED BY CODEGEN. DO NOT EDIT.

// Tag represents a row from 'tag'.
type Tag struct {
	codegen.Tag
}

// new implements Bindable.new
func (ta *Tag) new() Bindable {
	return &Tag{}
}

// helper struct for common query operations.
type TagSlice struct {
	data []*Tag
}

// append implements BindableSlice.append
func (ta *TagSlice) append(d Bindable) {
	ta.data = append(ta.data, d.(*Tag))
}

// constant slice for all fields of the table "Tag".
// nolint[gochecknoglobals]
var tagQueryFieldsAll = []string{"id", "name"}

// returns fields, that should be used.
// nolint[gocyclo]
func TagQueryFields(colSet *big.Int) []string {
	if colSet == nil {
		return tagQueryFieldsAll
	}

	fields := []string{}
	if colSet.Bit(codegen.Tag_ID) == 1 {
		fields = append(fields, "id")
	}

	if colSet.Bit(codegen.Tag_Name) == 1 {
		fields = append(fields, "name")
	}
	return fields
}

// TagStore is used to query for 'Tag' records.
type TagStore struct {
	Store
}

// NewTagStore return DAO Store for Tag
func NewTagStore(conn Execer) *TagStore {
	ta := &TagStore{}
	ta.db = conn
	ta.withJoin = true
	ta.joinType = sdb.LEFT
	ta.batch = 1000
	return ta
}

// WithoutJoins won't execute JOIN when querying for records.
func (ta *TagStore) WithoutJoins() *TagStore {
	ta.withJoin = false
	return ta
}

// Where sets local sql, that will be appended to SELECT.
func (ta *TagStore) Where(sql string) *TagStore {
	ta.where = sql
	return ta
}

// OrderBy sets local sql, that will be appended to SELECT.
func (ta *TagStore) OrderBy(sql string) *TagStore {
	ta.orderBy = sql
	return ta
}

// GroupBy sets local sql, that will be appended to SELECT.
func (ta *TagStore) GroupBy(sql string) *TagStore {
	ta.groupBy = sql
	return ta
}

// Limit result set size
func (ta *TagStore) Limit(n int) *TagStore {
	ta.limit = n
	return ta
}

// Offset used, if a limit is provided
func (ta *TagStore) Offset(n int) *TagStore {
	ta.offset = n
	return ta
}

// JoinType sets join statement type (Default: INNER | LEFT | RIGHT | OUTER).
func (ta *TagStore) JoinType(jt string) *TagStore {
	ta.joinType = jt
	return ta
}

// Columns sets bits for specific columns.
func (ta *TagStore) Columns(cols ...int) *TagStore {
	ta.Store.Columns(cols...)
	return ta
}

// SetBits sets complete BitSet for use in UpdatePartial.
func (ta *TagStore) SetBits(colSet *big.Int) *TagStore {
	ta.colSet = colSet
	return ta
}

// nolint[gocyclo]
func (ta *Tag) bind(row []sql.RawBytes, withJoin bool, colSet *big.Int, col *int) {
	BindFakeBenchmarkTag(&ta.Tag, row, withJoin, colSet, col)
}

func BindFakeBenchmarkTag(ta *codegen.Tag, row []sql.RawBytes, withJoin bool, colSet *big.Int, col *int) {
	if colSet == nil || colSet.Bit(codegen.Tag_ID) == 1 {
		ta.ID = sdb.ToInt(row[*col])
		*col++
	}
	if colSet == nil || colSet.Bit(codegen.Tag_Name) == 1 {
		ta.Name = sdb.ToString(row[*col])
		*col++
	}
}

func (ta *TagStore) selectStatement() *sdb.SQLStatement {
	sql := sdb.NewSQLStatement()
	sql.Append("SELECT")
	sql.Fields("", "A", TagQueryFields(ta.colSet))
	sql.Append(" FROM fake_benchmark.tag A")
	if ta.where != "" {
		sql.Append("WHERE", ta.where)
	}
	if ta.groupBy != "" {
		sql.Append("GROUP BY", ta.groupBy)
	}
	if ta.orderBy != "" {
		sql.Append("ORDER BY", ta.orderBy)
	}
	if ta.limit > 0 {
		sql.AppendRaw("LIMIT ", ta.limit)
		if ta.offset > 0 {
			sql.AppendRaw(",", ta.offset)
		}
	}
	return sql
}

// QueryCustom retrieves many rows from 'fake_benchmark.tag' as a slice of Tag with 1:1 joined data.
func (ta *TagStore) QueryCustom(stmt string, args ...interface{}) ([]*codegen.Tag, error) {
	dto := &Tag{}
	data := &TagSlice{}
	err := ta.queryCustom(data, dto, stmt, args...)
	if err != nil {
		log.Error().Err(err).Msg("querycustom")
		return nil, err
	}
	retValues := make([]*codegen.Tag, len(data.data))
	for i := range data.data {
		retValues[i] = &data.data[i].Tag
	}
	return retValues, nil
}

// One retrieves a row from 'fake_benchmark.tag' as a Tag with 1:1 joined data.
func (ta *TagStore) One(args ...interface{}) (*codegen.Tag, error) {
	data := &Tag{}

	err := ta.one(data, ta.selectStatement(), args...)
	if err != nil {
		log.Error().Err(err).Msg("query one")
		return nil, err
	}
	return &data.Tag, nil
}

// Query retrieves many rows from 'fake_benchmark.tag' as a slice of Tag with 1:1 joined data.
func (ta *TagStore) Query(args ...interface{}) ([]*codegen.Tag, error) {
	stmt := ta.selectStatement()
	return ta.QueryCustom(stmt.Query(), args...)
}

// Insert inserts the Tag to the database.
func (ta *TagStore) Insert(data *codegen.Tag) error {
	var err error
	sql := sdb.NewSQLStatement()
	sql.Append("INSERT INTO fake_benchmark.tag (")
	fields := TagQueryFields(ta.colSet)
	sql.Fields("", "", fields)
	sql.Append(") VALUES (")
	for i := range fields {
		if i > 0 {
			sql.Append(",")
		}
		sql.Append("?")
	}
	sql.Append(")")

	if zerolog.GlobalLevel() == zerolog.DebugLevel {
		log.Debug().Str("fn", "fake_benchmark.tag.Insert").Str("stmt", sql.String()).Int("ID", data.ID).Str("Name", data.Name).Msg("sql")
	}
	res, err := ta.db.Exec(sql.Query(), data.ID, data.Name)
	if err != nil {
		log.Error().Err(err).Msg("exec")
		return err
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		log.Error().Err(err).Msg("lastinsertid")
		return err
	}

	// set primary key and existence
	data.ID = int(id)

	return nil
}

// Update updates the Tag in the database.
// nolint[gocyclo]
func (ta *TagStore) Update(data *codegen.Tag) (int64, error) {
	sql := sdb.NewSQLStatement()
	var prepend string
	args := []interface{}{}
	sql.Append("UPDATE fake_benchmark.tag SET")
	if ta.colSet == nil || ta.colSet.Bit(codegen.Tag_Name) == 1 {
		sql.AppendRaw(prepend, "name = ?")
		args = append(args, data.Name)
	}
	sql.Append(" WHERE id = ?")
	args = append(args, data.ID)
	if zerolog.GlobalLevel() == zerolog.DebugLevel {
		log.Debug().Str("fn", "fake_benchmark.tag.Update").Str("stmt", sql.String()).Interface("args", args).Msg("sql")
	}
	res, err := ta.db.Exec(sql.Query(), args...)
	if err != nil {
		log.Error().Err(err).Msg("exec")
		return 0, err
	}
	return res.RowsAffected()
}

// Delete deletes the Tag from the database.
func (ta *TagStore) Delete(data *codegen.Tag) (int64, error) {
	var err error

	sql := sdb.NewSQLStatement()
	sql.Append("DELETE FROM fake_benchmark.tag WHERE")
	sql.Append("id = ?")

	if zerolog.GlobalLevel() == zerolog.DebugLevel {
		log.Debug().Str("fn", "fake_benchmark.tag.Delete").Str("stmt", sql.String()).Int("ID", data.ID).Msg("sql")
	}
	res, err := ta.db.Exec(sql.Query(), data.ID)
	if err != nil {
		log.Error().Err(err).Msg("exec")
		return 0, err
	}
	return res.RowsAffected()
}

// DeleteSlice delets all slice element from the database.
func (ta *TagStore) DeleteSlice(data []*codegen.Tag) (int64, error) {
	var err error

	sql := sdb.NewSQLStatement()
	sql.Append("DELETE FROM fake_benchmark.tag WHERE")
	sql.AppendRaw("id IN (")
	for i := range data {
		if i > 0 {
			sql.AppendRaw(",")
		}
		sql.AppendInt(data[i].ID)
	}
	sql.Append(")")
	if zerolog.GlobalLevel() == zerolog.DebugLevel {
		log.Debug().Str("fn", "fake_benchmark.tag.DeleteSlice").Str("stmt", sql.String()).Msg("sql")
	}
	res, err := ta.db.Exec(sql.Query())
	if err != nil {
		log.Error().Err(err).Msg("exec")
		return 0, err
	}
	return res.RowsAffected()
}

// DeleteByQuery uses a where condition to delete entries.
func (ta *TagStore) DeleteByQuery(args ...interface{}) (int64, error) {
	var err error
	sql := sdb.NewSQLStatement()
	sql.Append("DELETE FROM fake_benchmark.tag")
	if ta.where == "" {
		return 0, errors.New("no where condition set")
	}
	sql.Append("WHERE", ta.where)
	if zerolog.GlobalLevel() == zerolog.DebugLevel {
		log.Debug().Str("fn", "fake_benchmark.tag.DeleteByQuery").Str("stmt", sql.String()).Interface("args", args).Msg("sql")
	}

	res, err := ta.db.Exec(sql.Query())
	if err != nil {
		log.Error().Err(err).Msg("exec")
		return 0, err
	}
	return res.RowsAffected()
}

// Truncate deletes all rows from Tag.
func (ta *TagStore) Truncate() error {
	sql := sdb.NewSQLStatement()
	sql.Append("TRUNCATE fake_benchmark.tag")
	if zerolog.GlobalLevel() == zerolog.DebugLevel {
		log.Debug().Str("fn", "fake_benchmark.tag.Truncate").Str("stmt", sql.String()).Msg("sql")
	}
	_, err := ta.db.Exec(sql.Query())
	if err != nil {
		log.Error().Err(err).Msg("exec")
	}
	return err
}

// OneByID retrieves a row from 'fake_benchmark.tag' as a Tag.
//
// Generated from index 'primary'.
// nolint[goconst]
func (ta *TagStore) OneByID(id int) (*codegen.Tag, error) {
	ta.where = "A.id = ?"
	return ta.One(id)
}

// ToJSON writes a single object to the buffer.
// nolint[gocylco]
func (ta *TagStore) ToJSON(t *sdb.JsonBuffer, data *Tag) {
	prepend := "{"
	if ta.colSet == nil || ta.colSet.Bit(codegen.Tag_ID) == 1 {
		t.JD(prepend, "id", data.ID)
		prepend = ","
	}
	if ta.colSet == nil || ta.colSet.Bit(codegen.Tag_Name) == 1 {
		t.JS(prepend, "name", data.Name)
	}
	t.S(`}`)
}

// ToJSONArray writes a slice to the named array.
func (ta *TagStore) ToJSONArray(w io.Writer, data []*Tag, name string) {
	t := sdb.NewJsonBuffer()
	t.SS(`{"`, name, `":[`)
	for i := range data {
		if i > 0 {
			t.S(",")
		}
		ta.ToJSON(t, data[i])
	}

	t.S("]}")
	_, err := w.Write(t.Bytes())
	if err != nil {
		panic(err)
	}
}

// ^^ END OF GENERATED BY CODEGEN. DO NOT EDIT. ^^
