Package ="models"
DirOut="/home/sl/gocode/src/bitbucket.com/kanban/models/"
FilePattern ="%s.xo.go"
Templates  = [ "header", "type", "" ]

[Database]
	DSN  = "root@/?parseTime=true"
	Schemas =  [ "kanban" ]