package db

import (
	"database/sql"

	"bitbucket.org/codegen"
)

// GENERATED BY CODEGEN. DO NOT EDIT.
// ^^ END OF GENERATED BY CODEGEN. DO NOT EDIT. ^^

/* ExtensiveRepo implemente ExtensiveRepository interface definition. */
type ExtensiveRepo struct {
	conn *sql.DB
}

func NewExtensiveRepo(conn *sql.DB) *ExtensiveRepo {
	return &ExtensiveRepo{
		conn: conn,
	}
}

func (r ExtensiveRepo) Create(data *codegen.Extensive) error {
	panic("not implemented")
}

func (r ExtensiveRepo) Update(data *codegen.Extensive) error {
	panic("not implemented")
}

func (r ExtensiveRepo) UpdatePartial(data *codegen.ExtensivePartial) error {
	panic("not implemented")
}

func (r ExtensiveRepo) Delete(data *codegen.Extensive) error {
	panic("not implemented")
}

func (r ExtensiveRepo) Upsert(data []*codegen.Extensive) error {
	panic("not implemented")
}

func (r ExtensiveRepo) OneByID(id int) (*codegen.Extensive, error) {
	panic("not implemented")
}
