package db

import (
	"database/sql"

	"bitbucket.org/codegen"
)

// GENERATED BY CODEGEN.
// ^^ END OF GENERATED BY CODEGEN. ^^

/* PersonRepo implemente PersonRepository interface definition. */
type PersonRepo struct {
	conn *sql.DB
}

func NewPersonRepo(conn *sql.DB) *PersonRepo {
	return &PersonRepo{
		conn: conn,
	}
}

func (r PersonRepo) Create(data *codegen.Person) error {
	panic("not implemented")
}

func (r PersonRepo) Update(data *codegen.Person) error {
	panic("not implemented")
}

func (r PersonRepo) UpdatePartial(data *codegen.PersonPartial) error {
	panic("not implemented")
}

func (r PersonRepo) Delete(data *codegen.Person) error {
	panic("not implemented")
}

func (r PersonRepo) Upsert(data []*codegen.Person) error {
	panic("not implemented")
}

func (r PersonRepo) OneByID(id int) (*codegen.Person, error) {
	panic("not implemented")
}
