package db

import (
	"database/sql"

	"github.com/seambiz/codegen"
	"github.com/seambiz/codegen/db/mysql"
)

// GENERATED BY CODEGEN.

/* StatisticsRepo implements StatisticsRepository interface definition. */
type StatisticsRepo struct {
	conn *sql.DB
}

func NewStatisticsRepo(conn *sql.DB) codegen.StatisticsRepository {
	return &StatisticsRepo{
		conn: conn,
	}
}

// ^^ END OF GENERATED BY CODEGEN. ^^

func (r StatisticsRepo) IndexNameBySchemaAndTable(ctx *codegen.Context, schema, table string) ([]*codegen.Statistics, error) {
	store := mysql.NewStatisticsStore(ctx, r.conn)
	store.Columns(codegen.Statistics_IndexName)
	return store.Where("UPPER(table_schema) = UPPER(?) AND UPPER(table_name) = UPPER(?)").
		GroupBy("index_name").
		Query(schema, table)
}

func (r StatisticsRepo) QueryBySchemaAndTableAndIndex(ctx *codegen.Context, schema, table, index string) ([]*codegen.Statistics, error) {
	return mysql.NewStatisticsStore(ctx, r.conn).
		Where("UPPER(table_schema) = UPPER(?) AND UPPER(table_name) = UPPER(?) AND UPPER(index_name) = UPPER(?)").
		OrderBy("seq_in_index").
		Query(schema, table, index)
}
