package db

import (
	"database/sql"

	"bitbucket.org/codegen"
	"bitbucket.org/codegen/db/mysql"
)

// GENERATED BY CODEGEN. DO NOT EDIT.
// ^^ END OF GENERATED BY CODEGEN. DO NOT EDIT. ^^

/* StatisticsRepo implemente StatisticsRepository interface definition. */
type StatisticsRepo struct {
	conn *sql.DB
}

func NewStatisticsRepo(conn *sql.DB) *StatisticsRepo {
	return &StatisticsRepo{
		conn: conn,
	}
}

func (r StatisticsRepo) Create(ctx *codegen.BaseContext, data *codegen.Statistics) error {
	panic("not implemented")
}

func (r StatisticsRepo) Update(ctx *codegen.BaseContext, data *codegen.Statistics) error {
	panic("not implemented")
}

func (r StatisticsRepo) UpdatePartial(ctx *codegen.BaseContext, data *codegen.StatisticsPartial) error {
	panic("not implemented")
}

func (r StatisticsRepo) Delete(ctx *codegen.BaseContext, data *codegen.Statistics) error {
	panic("not implemented")
}

func (r StatisticsRepo) Upsert(ctx *codegen.BaseContext, data []*codegen.Statistics) error {
	panic("not implemented")
}

func (r StatisticsRepo) IndexNameBySchemaAndTable(ctx *codegen.BaseContext, schema, table string) ([]*codegen.Statistics, error) {
	store := mysql.NewStatisticsStore(ctx, r.conn)
	store.Columns(codegen.Statistics_IndexName)
	return store.Where("UPPER(table_schema) = UPPER(?) AND UPPER(table_name) = UPPER(?)").
		GroupBy("index_name").
		Query(schema, table)
}

func (r StatisticsRepo) QueryBySchemaAndTableAndIndex(ctx *codegen.BaseContext, schema, table, index string) ([]*codegen.Statistics, error) {
	return mysql.NewStatisticsStore(ctx, r.conn).
		Where("UPPER(table_schema) = UPPER(?) AND UPPER(table_name) = UPPER(?) AND UPPER(index_name) = UPPER(?)").
		OrderBy("seq_in_index").
		Query(schema, table, index)
}
