package db

import (
	"database/sql"

	"bitbucket.org/codegen"
	"bitbucket.org/codegen/db/mysql"
)

// GENERATED BY CODEGEN.

/* TablesRepo implements TablesRepository interface definition. */
type TablesRepo struct {
	conn *sql.DB
}

func NewTablesRepo(conn *sql.DB) codegen.TablesRepository {
	return &TablesRepo{
		conn: conn,
	}
}

// ^^ END OF GENERATED BY CODEGEN. ^^

func (r TablesRepo) QueryBySchema(ctx *codegen.Context, schema string) ([]*codegen.Tables, error) {
	return mysql.NewTablesStore(ctx, r.conn).
		Where("UPPER(table_schema) = UPPER(?) AND table_type IN (UPPER('base table'), UPPER('system view'))").
		Query(schema)
}
