package templates

import (
	"bitbucket.org/codegen"
	"bitbucket.org/codegen/gen"
)

func Generate(conf codegen.Config) {
	g := gen.NewGenerator()

	g.Package(conf.RootPackage)
	g.Comment("GENERATED BY CODEGEN.")
	g.Comment("Constants for table columns")
	g.Line()
	g.Go("const (")

	iotaSet := false
	for _, schema := range conf.Schemas {
		for _, t := range schema.Tables {
			if t.Generate {
				g.Comment("Columns for table ", t.Name, ".", t.Title)
				for _, f := range t.Fields {
					if iotaSet {
						g.Go(t.Title, "_", f.Title)
					} else {
						g.Go(t.Title, "_", f.Title, " = iota")
						iotaSet = true
					}
				}
			}
		}
	}
	g.Line()
	g.Comment("^^ END OF GENERATED BY CODEGEN. ^^")
}
